---
title: "Historic Image Analysis"
author: "Trudy Boan"
date: "2022-10-15"
output: html_document
---

\

<div class="alert alert-info" role="alert">
#### Aerial photograph of St Helena prison 
</div> 

![Brisbane City Council (1920) *Aerial photograph of St Helena prison in the 1920s* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23184/0)*,* Brisbane City Council website, © Brisbane Images, Brisbane City Council. This Copyright has expired. This image may be reproduced with acknowledgement, accessed 12 October 2022.](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23184/0){alt="Brisbane City Council (1920) Aerial photograph of St Helena prison in the 1920s [photograph], Brisbane Images, Brisbane City Council website, © Brisbane Images, Brisbane City Council. This Copyright has expired. This image may be reproduced with acknowledgement, accessed 12 October 2022."}

\

**This aerial photograph of the St Helena Penal Establishment focuses on the buildings surrounding the stockade, as the island is much larger than shown. This image is significant to the case study as it shows the scale and the layout of a section of the Penal Establishment. It shows the stockade's layout, which may have previously only been seen in 2-dimensional plans, and probably not available to the public. The stockade is relatively small when compared to the warder's accommodation, on the right of the picture. The photo gives an impression of the scale of the crops grown on the island, showing many large parcels of land that were worked by inmates. The picture also shows a small portion of the mangroves surrounding the island, which deter would-be escapees. I think the picture dates from the early 20^th^ century, well between 1912 and 1932, when the Penal Establishment closed. The picture may well have been taken when the closure was announced.**

\

<div class="alert alert-info" role="alert">
#### Corridor 'D' Wing, St Helena Penal Establishment 
</div>

![Brisbane City Council (1915) *Corridor 'D' Wing, St Helena Penal Establishment* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23182/0), Brisbane City Council website, © Brisbane Images, Brisbane City Council. This Copyright has expired. This image may be reproduced with acknowledgement, accessed 12 October 2022.](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23182/0)

\

**This image is significant to the case study as it is a rare glimpse into the inner sanctum of the prison. The inmate stands in a corridor between cells. The cells are numbered, with the tongue and groove timber walls displaying the security of the building. The staged image would have been used to promote the Penal Establishment as a model establishment. The image is an insight into what the inmates saw every day, which was not shared widely with the public.**

\

<div class="alert alert-info" role="alert">
#### Land under cultivation, St. Helena penal establishment 
</div>

![Brisbane City Council (1890) *Land under cultivation, St. Helena penal establishment* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23407/0), Brisbane City Council website, © Brisbane Images, Brisbane City Council. This Copyright has expired. This image may be reproduced with acknowledgement, accessed 12 October 2022.](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23407/0)

\

**This image is significant to the case study as it shows the three most crucial elements of the Penal Establishment in one shot. The sugar mill has been positioned in the background, with the stockade to the right, and the crops in the foreground. The crops are important in making the Penal Island self-sufficient and providing a place of employment for inmates who work toward reforming their characters. The variety of crops grown is shown in the picture, along with inmates who appear to have some freedom, as there are no warders to be seen and they are not wearing irons. With the lack of supervision and the well-established crops and cleared land, the picture was probably taken around the turn of the century and gives a visual description of life on the island.**

\

<div class="alert alert-info" role="alert">
#### Prison cell 
</div>

![Cathy Cooper (2020) *Prison cell* [photograph], [*St Helena Island National Park*](https://www.google.com/maps/uv?pb=!1s0x6b93dfbbe18c8ef5%3A0x29c9140524331d61!3m1!7e164!15sCgIgAQ&hl=en&viewerState=ga&imagekey=!1e10!2sAF1QipOjxYz9FzSt2YTDv3aYUnhtDeYoYqC_hVA5gm0), Google Maps website, Copyright free, accessed 23 October 2022.](pics%20for%20assessment/images/Prison%20cell.png)

\

**This photo is of a replica cell from the Penal Establishment. The cell is very small, with no items, other than a hammock that inmates sleep on. It is very cramped and would be very depressing to be in for 10 to 12 hours a day. The cell is a replica of an early cell, as later inmates had 'comforts,' a chair, and a table. This image is significant to the case study as it gives insight into the inmates' daily and private lives. I do not think many photos would have been taken of the cells, a restricted area. The thick timber door with steel bars looks very intimidating and secure, it would have made the inmates feel there was definitely no escape.**

\

<div class="alert alert-info" role="alert">
#### Sisal hemp, raspador, silos, and old chimney 
</div>

![Brisbane City Council (1915) *Sisal hemp, raspador, silos and old chimney, St Helena Penal Establishment* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23150/0), Brisbane City Council website, © Brisbane Images, Brisbane City Council. This Copyright has expired. This image may be reproduced with acknowledgement, accessed 12 October 2022.](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23150/0)

\

**This image places its focus on two inmates at work with a belt run machine, dwarfed by a large brick chimney. The inmates are not wearing leg irons, in fact, they look like ordinary men working in an ordinary farm environment. The building to the right is falling apart, which could be an indicator of its age. That would place the image around the turn of the century. The men are wearing the prison uniform, with the cabbage hat worn by farm workers. They do not have their prison numbers on their uniforms, which would place the image closer to the 1920s when St Helena was a low-security prison farm. The context of the image is showing men being industrious, using industrial machinery; rather than sitting around in cell blocks and costing money, they are making money for the island officials. The men appear to be using the raspador machine to make rope and other items which could be used by other trades in the production of their goods. This image is significant to the case study as it illustrates men working, freely, producing goods for the establishment and profit.**

\

<div class="alert alert-info" role="alert">
#### Tailor's shop 
</div>#### [******]{.underline}

![Brisbane City Council (1915) *Tailor's shop, St Helena Penal Establishment* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23139/0), Brisbane City Council website, © Brisbane Images, Brisbane City Council. This Copyright has expired. This image may be reproduced with acknowledgement, accessed 12 October 2022.](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23139/0)

\

**The image shows the men being instructed in the trade of tailoring. Some of their tools lie on the table in the foreground. This is a good image to send to Brisbane, to show the men at work in the large workhouse. The warder in the foreground to the right appears to be walking down an aisle, for instruction or surveillance. On the back of the men's shirt is their prisoner number, which was allocated to them upon entry, via Brisbane gaol. The smartly dressed man could be a superintendent or the chief superintendent, as they are not wearing the warder's uniform. This photo shows one of the trades of the establishment which makes a nice change to the predominantly written descriptions. The image provides insight into the men's working day and the working conditions, and therefore, has significance to the case study.**

\

::: {.alert .alert-info role="alert"}
#### Tree clearing
:::

![Brisbane City Council (1868) *Tree clearing on St Helena Island* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23385/0), Brisbane City Council website, © Brisbane Images, Brisbane City Council. This Copyright has expired. This image may be reproduced with acknowledgement, accessed 12 October 2022.](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23385/0)

\

**This image is significant to the case study as it illustrates what the early inmates faced, clearing an island of trees, and the hard life of the first inmates. Composing the image with the fallen trees in the foreground and standing trees in the background shows what a big job was still in front of the men. This photo would have been taken around the mid-1800s when the island was being prepared as a quarantine station, but quickly changed direction to a Penal Establishment. Isolation can almost be felt through the image. Contextually, the image could illustrate the isolation of the island, report progress back to Brisbane, or simply for posterity. The image shows the beginning of the island's development.**

\
\

#### [*Links*]{.underline}

\
[Reference list for all images

[Zotero report for all images

[Zotero report for analysed images]
