---
title: "References"
author: "Trudy Boan"
date: "2022-09-05"
output: html_document
---

A paying guest (12 February 1911) '[Penal Establishment and health resort: High life and hell](http://nla.gov.au/nla.news-article201756402,)', *Truth*, accessed 1 October 2022.

A paying guest (5 February 1911) '[Penal Establishment or Health Resort? High Life or Hell, Which](http://nla.gov.au/nla.news-article201758420)?', *Truth*, accessed 31 October 2022.

Alfredson G (1983) 'St Helena Island - A Changing Pattern of Exploitation?', *Australian Archaeology*, 17(1):79--86, [doi:[10.1080/03122417.1983.12092912](doi:%5B10.1080/03122417.1983.12092912){.uri}](https://doi.org/10.1080/03122417.1983.12092912).

Ancestry.com (n.d.) [*Queensland, Australia, Death Inquest Index, 1859-1897*](https://www.ancestry.com.au/search/collections/70807/), Ancestry.com website, accessed 3 September 2022.

Australian Government (n.d.) [*NationalMap*](https://nationalmap.gov.au/), National Map website, accessed 4 September 2022.

Baron Douglas-Scott-Montagu HJ (1853) *St. Helena, Moreton Bay* [artwork], [*St. Helena, Moreton Bay, 20th July, 1853*](https://nla.gov.au/nla.obj-134723485/view), Trove website, accessed 11 October 2022.

Beatty B (13 December 1941) '[Convicts Foiled](https://nla.gov.au/nla.obj-1266892874,)', *The ABC Weekly,* accessed 26 October 2022.

Bochenski N (9 December 2013) '[Painting of St Helena reveals colour of Brisbane's prison past](https://www.brisbanetimes.com.au/national/queensland/painting-of-st-helena-reveals-colour-of-brisbanes-prison-past-20131209-2z1h4.html)', *Brisbane Times website*, accessed 27 October 2022.

Boggo Road Gaol Historical Society (n.d.) '[St Helena Island Penal Establishment (1867-1932)](https://www.boggoroadgaol.com.au/2015/10/st-helena-island.html)', *Inside Boggo Road blog*, accessed 30 October 2022.

Brisbane City Council (1868) *Tree clearing on St Helena Island* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/), Brisbane City Council Archives website, accessed 11 October 2022.

------ (1890) *Land under cultivation, St. Helena penal establishment* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23407/0), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1893) *Mug shots of prisoners associated with the Barcaldine Shearers' Strike* [photograph], [*Queensland Police Museum*](https://ehive.com/collections/3606/objects/553427/mug-shots-of-prisoners-associated-with-the-barcaldine-shearers-strike), eHive website, accessed 20 October 2022.

------ (1912a) *Bootmaker's shop, H.M. Penal establishment, St Helena* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23161/0), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1912b) *Saddler's shop, H.M. Penal Establishment, St Helena* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23143/0), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1915a) *Backview of stockade, St Helena Penal Establishment* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23186/0), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1915b) *Corridor 'D' Wing, St Helena Penal Establishment* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23182/0), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1915c) *Old signal gun, St Helena Penal Establishment 24 pounder* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/client/en_AU/search/asset/23136/0), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1915d) *Sisal hemp, raspador, silos and old chimney, St Helena Penal Establishment* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1915e) *Tailor's shop, St Helena Penal Establishment* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1920a) *Aerial photograph of St Helena prison in the 1920s* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1920b) *North cell block, St Helena Island, 1920s* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1930) *The prison vegetable garden, St Helena Island* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/), Brisbane City Council Archives website, accessed 12 October 2022.

------ (1937) *Sugar mill, St Helena Island* [photograph], [*Brisbane Images*](https://library-brisbane.ent.sirsidynix.net.au/), Brisbane City Council Archives website, accessed 12 October 2022.

Brismania (2019) '[Day 148: Captive audience](https://brismania.com/day-148-captive-audience/)', *Brismania blog*, accessed 30 October 2022.

Bull J (1 January 1960) '[The Alcatraz of Moreton Bay'](https://nla.gov.au/nla.obj-749108297), *Walkabout*, Trove website 26 October 2022.

Carter R (n.d.) [*Geographic Information Systems (GIS): Datasets & Maps*](https://libguides.usc.edu.au/c.php?g=711636&p=5063784), University of the Sunshine Coast guides website, accessed 4 September 2022.

Cooper C (2020) *Prison cell* [photograph], [*St Helena National Park*](https://www.google.com/maps), Google Maps contributor website, accessed 23 October 2022.

Cope M (2019) *The Black Napoleon* [artwork], [*The Black Napoleon*](https://www.megancope.com.au/works/the-black-napoleon), Megan Cope website, accessed 21 October 2022.

CyArk (1894) *Building plan, St Helena* [sketch], [*Building the prison*](https://www.cyark.org/projects/st-helena-island-national-park), CyArk projects website, accessed 20 October 2022.

Daly B (2019) '[The Wild Scotchman Part 2](https://sthelenacommunity.com.au/2019/04/15/the-wild-scotchman-part-2/)', *The St Helena Island Community blog*, accessed 29 October 2022.

Department of Climate Change, Energy, the Environment and Water (n.d.) [*St Helena Island National Park Historic Area*](https://www.environment.gov.au), Australian Heritage Database website, accessed 30 October 2022.

Department of Environment and Science (2005) [*Nature, culture and history: St Helena Island National Park*](https://parks.des.qld.gov.au/parks/st-helena-island/about/culture,), Parks and forests website, accessed 30 October 2022.

Department of Resources (n.d.) [*Data and mapping*](https://www.resources.qld.gov.au/data-mapping), Department of resources website, accessed 4 September 2022.

Findmypast (n.d.) [*Search Results for Queensland, St Helena Convict Index 1863-1936*](https://www.findmypast.com/search/results?datasetname=queensland%2c+st+helena+convict+index+1863-1936&sid=103), Findmypast website, accessed 22 October 2022.

Geoscience Australia (n.d.) [*Location information about Australia's dimensions, landforms and national mapping*](https://www.ga.gov.au/scientific-topics/national-location-information), National Location Information website, accessed 4 September 2022.

Gray J (2012) *Saint Helena Island prisoner cemetery* [photograph], [*Tour of Saint Helena Island (Ex-Convict Prison) 04/05/12*](http://beyondourpatch.blogspot.com/2012/05/tour-of-saint-helena-island-ex-convict.html), Beyond Our Patch - Australian Birds Environment Wildlife Travel & Conservation blog, accessed 21 October 2022.

Gray J (2012) *St Helena original prison door and lock* [photograph], [*Tour of Saint Helena Island (Ex-Convict Prison) 04/05/12*](http://beyondourpatch.blogspot.com/2012/05/tour-of-saint-helena-island-ex-convict.html), Beyond Our Patch - Australian Birds Environment Wildlife Travel & Conservation blog, accessed 21 October 2022.

Greenhill J (25 February 2022) '[St Helena, formerly "the hell hole of the pacific](https://thecommunityleader.com.au/community-news/local-history/st-helena-formerly-the-hell-hole-of-the-pacific/)"', *The Community Leader and Real Estate New and Views*, accessed 30 October 2022.

Hendrik (2013) [*The Evolution of the Necktie*](https://www.tie-a-tie.net/the-evolution-of-the-necktie/), Tie-A-Tie website, accessed 27 October 2022.

Hopkins-Weise J and Pratt R (2002) 'The 50th (Queen's Own) Regiment Military Guard at the St Helena Penal Establishment, Moreton Bay, 1867-69', *Journal of the Royal Historical Society of Queensland*, 18(3):97--114, [doi:[10.3316/ielapa.200302240](doi:%5B10.3316/ielapa.200302240){.uri}](https://doi.org/10.3316/ielapa.200302240).

Irving A (1914) *St Helena Penal Establishment - new penitentiary* [sketch], [*St Helena Penal Establishment - New penitentiary, book of 17 plans, reduced scale from linen tracings - Public Works Department (II)*](https://www.archivessearch.qld.gov.au/items/ITM328272), Queensland Governmnt ArchivesSearch website, accessed 21 October 2022.

Jepson D (2019) *St Helena prison guide* [photograph], [*St Helena National Park*](https://www.google.com/maps), Google Maps contributor website, accessed 23 October 2022.

K S (9 November 1901) '[The Isle of Unrest: H.M. Penal Establishment, St. Helena](http://nla.gov.au/nla.news-article21268213)', *Queenslander*, accessed 31 October 2022.

Kerkhove R (1 January 2018) [*Eulope (Napoleon) and the Battle of Moongalba (Stradbroke Island)*](https://www.academia.edu/59411218/EULOPE_NAPOLEON_AND_THE_BATTLE_OF_MOONGALBA_STRADBROKE_ISLAND_Script_for_Life_in_Irons_Exhibition_Museum_of_Brisbasne), Museum of Brisbane, accessed 2 August 2022.

Kerkhove R (n.d.) [*Eulope (c. 1800--c. 1840)*](https://ia.anu.edu.au/biography/eulope-32070), Indigenous Australia website, accessed 26 October 2022.

Keys C (2020) 'Sharing the waterways: Shark-proof swimming, penal detention and the early history of St Helena Island, Moreton Bay', *Queensland Review*, 27(2):121--136, [doi:[10.1017/qre.2020.11](doi:%5B10.1017/qre.2020.11){.uri}](https://doi.org/10.1017/qre.2020.11).

King B (2019) *Swimming pool* [photograph], [*Photos of St Helena Island National Park*](https://www.tripadvisor.com.au/Attraction_Review-g3208744-d263371-Reviews-St_Helena_Island_National_Park-Moreton_Bay_Region_Brisbane_Region_Queensland.html#/media-atf/263371/379830131:p/?albumid=-160&type=0&category=-160), Tripadvisor website, accessed 12 October 2022.

Levez J (2016) [*Prisoner #3650 Jimmy*](https://billiongraves.com/grave/Prisoner-%233650-Jimmy/18398259), BillionGraves website, accessed 24 October 2022.

Levez J (2016) *St Helena Penal Establishment prisoner cemetery information board* [photograph], [*St Helena Penal Establishment Prisoner cemetery*](http://www.australiancemeteries.com.au/qld/brisbane/st_helena/img_0389lge.jpg), Australian cemeteries website, accessed 9 October 2022.

Levez J (n.d.) [*St Helena Penal Establishment Prisoners Cemetery*](https://billiongraves.com/cemetery/St-Helena-Penal-Establishment-Prisoners-Cemetery/294279), BillionGraves website, accessed 17 October 2022.

Matthews M (2016) [*A Century of Sartorial Style: A Visual Guide to 19th Century Menswear*](https://www.mimimatthews.com/2016/10/03/a-century-of-sartorial-style-a-visual-guide-to-19th-century-menswear/), Mimi Matthews website, accessed 26 October 2022.

Miller S (2013) '[Hold the line please - Brisbane Telephone Exchange](https://www.slq.qld.gov.au/blog/hold-line-please-brisbane-telephone-exchange)', *State Library of Queensland blog*, accessed 26 October 2022.

Molloy S (18 September 2007) '[St Helena Island the "hell-hole of Pacific](https://www.brisbanetimes.com.au/national/queensland/st-helena-island-the-hell-hole-of-pacific-20070918-ge93t1.html,)', *Brisbane Times*, accessed 28 October 2022.

Moreton Bay Police (1887) *General record and description of male prisoners* [photograph of document], [*General record and description of male prisoners - HM Penal Establishment, St Helena*](https://www.archivessearch.qld.gov.au/items/ITM271423), Queensland Government ArchivesSearch website, accessed 20 October 2022.

Moreton Bay Regional Council (n.d.) [*Datahub*](https://datahub.moretonbay.qld.gov.au/), Moreton Bay Regional Council, accessed 4 September 2022.

National Library of Australia (1951) *Australia's St Helena, Queensland hell hole of the Pacific* [photograph], [*Pix Magazine*](https://catalogue.nla.gov.au/Record/1414022), National library of Australia website, accessed 21 October 2022.

National Library of Australia (1870) *Penal station at St. Helena, Moreton Bay, Queensland* [artwork], [*The many lives of Moreton bay*](https://catalogue.nla.gov.au/Record/1890845), National library of Australia website, accessed 11 October 2022.

Natural Earth (n.d.) '[Downloads](https://www.naturalearthdata.com/downloads/)', *Natural Earth blog*, accessed 4 September 2022.

Nawaz F (2017) *Punishment list* [photograph], [*St Helena National Park*](https://www.google.com/maps), Google Maps contributor website, accessed 23 October 2022.

Out of bond (26 July 1914) '[Prisoners fed on sour prog. Confinee's complaints](http://nla.gov.au/nla.news-article202665223)', *Truth*, accessed 31 October 2022.

Pascoe W and Pascoe F (1871) *Sketch of the interior of the sugar house at St. Helena* [sketch], [*Collections*](https://hdl.handle.net/10462/deriv/193649), State Library of Queensland website, accessed 12 October 2022.

Proscriptus (8 September 1912) '[Tyrants of St. Helena: Some facts & reflections about Queensland's inferno'](http://nla.gov.au/nla.news-article201742089), *Truth*, accessed 26 October 2022.

Queensland Government (2015) [*Saint Helena Island*](https://apps.des.qld.gov.au/heritage-register/detail/?id=600315), Queensland Heritage Register website, accessed 25 October 2022.

Queensland Government (2022) '[Inquests 1859 to 1902](https://www.data.qld.gov.au/dataset/inquests-1859-to-1902)', *Communities, Housing and Digital Economy*, Queensland Government Open Data Portal website, accessed 12 October 2022.

Queensland Government (n.d.) *'[Barker George](https://www.archivessearch.qld.gov.au/items/ITM2732765)*', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Billy](https://www.archivessearch.qld.gov.au/items/ITM2731612)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Chick John](https://www.archivessearch.qld.gov.au/items/ITM2723189)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Collins Edward](https://www.archivessearch.qld.gov.au/items/ITM2735171)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Collins William](https://www.archivessearch.qld.gov.au/items/ITM2725725)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Coronial Files (Inquests and No Inquests)](https://www.archivessearch.qld.gov.au/series/S36)', *Coroners Court*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Crown Tim](https://www.archivessearch.qld.gov.au/items/ITM2733594)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Data portals*](https://www.data.qld.gov.au/dataset?organization=environment-and-science), Open data portal website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Dean Henry](https://www.archivessearch.qld.gov.au/items/ITM2732771)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Downs Archibald](https://www.archivessearch.qld.gov.au/items/ITM2731328)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Family history research service*](https://www.familyhistory.bdm.qld.gov.au/,), Births, deaths, marriages, and divorces website, accessed 22 October 2022.

Queensland Government (n.d.) *'*[Forka](https://www.archivessearch.qld.gov.au/items/ITM2735702)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.a) '[General record and description of male prisoners - HM Penal Establishment, St Helena](https://www.archivessearch.qld.gov.au/items/ITM92277)*'*, *General Records and Description of Prisoners*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.b) '[General record and description of male prisoners - HM Penal Establishment](http://www.archivessearch.qld.gov.au/Search/ItemDetails.aspx?ItemId=92278)*,* St Helena', *General Records and Description of Prisoners*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Hayes John](https://www.archivessearch.qld.gov.au/items/ITM2725548)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Herrlick John](https://www.archivessearch.qld.gov.au/items/ITM2723358)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Jamerson William](https://www.archivessearch.qld.gov.au/items/ITM2734778)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Jimmy](https://www.archivessearch.qld.gov.au/items/ITM2730160)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Jones John](https://www.archivessearch.qld.gov.au/items/ITM2723056)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Loder John](https://www.archivessearch.qld.gov.au/items/ITM2722068)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Lover Samuel](https://www.archivessearch.qld.gov.au/items/ITM2729740)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Mayall George](https://www.archivessearch.qld.gov.au/items/ITM2733865)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[McGoldrich Samuel](https://www.archivessearch.qld.gov.au/items/ITM2731103)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Mitchel Joseph](https://www.archivessearch.qld.gov.au/items/ITM2731742)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Moore George](https://www.archivessearch.qld.gov.au/items/ITM2729269)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Moss Valentine](https://www.archivessearch.qld.gov.au/items/ITM2722925)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Muller Harry](https://www.archivessearch.qld.gov.au/items/ITM2736026)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Museum of Lands, Mapping and Surveying*](https://www.qld.gov.au/recreation/arts/heritage/museum-of-lands), Heritage website, accessed 4 September 2022.

Queensland Government (n.d.) *'*[Potts William](https://www.archivessearch.qld.gov.au/items/ITM2727699)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Rahree](https://www.archivessearch.qld.gov.au/items/ITM2735293)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Rickaby Henry](https://www.archivessearch.qld.gov.au/items/ITM2733765)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Stapleton Thomas](https://www.archivessearch.qld.gov.au/items/ITM2733864)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Tidy Richard](https://www.archivessearch.qld.gov.au/items/ITM2723032)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Tommah Tom](https://www.archivessearch.qld.gov.au/items/ITM2728493)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) *'*[Waipieta David](https://www.archivessearch.qld.gov.au/items/ITM2731612)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Welcome to the Queensland Spatial Catalogue*](https://qldspatial.information.qld.gov.au/catalogue/custom/index.page), Queensland Spatial Catalogue - QSpatial, , accessed 4 September 2022.

Queensland Government (n.d.) *'*[Wyndham John](https://www.archivessearch.qld.gov.au/items/ITM2723432)', *Inquest file*, Queensland Government ArchivesSearch website, accessed 27 October 2022.

Queensland Parks and Wildlife Service, Department of National Parks, Sport and Racing (2015) St Helena Island National Park map [map], [*Queensland Parks and Wildlife Service*](https://parks.des.qld.gov.au/__data/assets/pdf_file/0015/160440/st_helena_map.pdf), Queensland Parks and Wildlife Service website, accessed 11 October 2022.

Queensland Parliament Legislative Assembly (1887) Plan of the island of St. Helena, H.M. Penal Establishment, Queensland [map], [*Prisons - Queensland - St. Helena Island -- Maps*](http://nla.gov.au/nla.obj-232189719), National Library of Australia website, accessed 11 October 2022.

Queensland State Archives (2016) '[The Not-So-Great-Escape](https://blogs.archives.qld.gov.au/2016/04/26/the-not-so-great-escape/)', *Stories from the Archives blog*, accessed 28 October 2022.

Queensland State Archives (2021) '[Escape from St Helena Island](https://blogs.archives.qld.gov.au/2021/04/21/escape-from-st-helena-island/)', *Stories from the Archives blog*, accessed 27 October 2022.

Queensland State Archives (2021) '[Shear power: Shearer's strike of 1891](https://blogs.archives.qld.gov.au/2021/12/21/shear-power-shearers-strike-of-1891/)', *Stories from the Archives blog*, accessed 26 October 2022.

Queensland State Archives (2021) Escape from St Helena Island[photograph], [*Queensland Police Gazette*](https://www.archivessearch.qld.gov.au/items/ITM519924), Queensland Government ArchivesSearch website, accessed 15 October 2022.

Queensland State Archives (n.d.) [*Queensland Parks and Wildlife Service*](https://www.archivessearch.qld.gov.au/agencies/A1441), Queensland Government Archive Search website, accessed 26 October 2022.

Rasputin C (2017) *Model of St Helena prison* [photograph], [*St Helena National Park*](https://www.google.com/maps), Google Maps contributor website, accessed 23 October 2022.

Rasputin C (2017) *Prisoner's private life* [photograph], [*St Helena National Park*](https://www.google.com/maps), Google Maps contributor website, accessed 23 October 2022.

Russell A (2017) *Work station* [photograph], [*St Helena National Park*](https://www.google.com/maps), Google Maps contributor website, accessed 23 October 2022.

Scholz Electrical (2021) [*Electricity in Australia and Overseas from 1882*](https://scholzelectrical.com.au/blog/electricity-in-australia-and-overseas-from-1882/), Scholz Electrical website, accessed 25 October 2022.

Snow F (1 November 1935) '[St Helena](https://nla.gov.au/nla.obj-721573586)', *Walkabout*, Trove website, accessed 26 October 2022.

SpacePrez (n.d.) [*FeatureCollection list*](https://asgs.linked.fsdf.org.au/dataset/asgsed3/collections), Australian Statistical Geography Standard Linked Data API website, accessed 4 September 2022.

State Library of Queensland (1893) *Freed unionist shearers following the 1891 shearers' strike* [photograph], [*Collections*](https://hdl.handle.net/10462/deriv/132229), State Library Queensland, accessed 11 October 2022.

Taylor B (2010) [*Prisons without walls: Prison camps and penal change in Australia, c. 1913-c. 1975*](https://doi.org/10.26190/unsworks/23117) [PhD Doctorate], University of NSW, Sydney, accessed 6 October 2022.

The Geological Survey of Queensland (GSQ) (n.d.) [*GIS datasets*](https://www.business.qld.gov.au/industries/mining-energy-water/resources/geoscience-information/maps-datasets/digital-data/gis), Business Queensland website, accessed 4 September 2022.

The Spacial Information Council (ANZLIC) (n.d.) [*Foundation Spatial Data Framework LINK Platform*](https://link.fsdf.org.au/), Australian Foundation Spatial Data website, accessed 4 September 2022.

Toni D (2017) *St Helena prisoner grave* [photograph], [*St Helena National Park*](https://www.tripadvisor.com.au/Attraction_Review-g3208744-d263371-Reviews-St_Helena_Island_National_Park-Moreton_Bay_Region_Brisbane_Region_Queensland.html#/media-atf/263371/262939595:p/?albumid=-160&type=0&category=-160), Tripadvisor website, accessed 21 October 2022.

Unknown (13 January 1869) '[From the Courier](http://nla.gov.au/nla.news-article75459987).', *Darling Downs Gazette and General Advertiser*, accessed 29 October 2022.

Unknown (20 August 1905) '[St. Helena scandals](http://nla.gov.au/nla.news-article198987032)', *Truth*, accessed 9 October 2022.

Unknown (20 March 1878) '[Life at St. Helena](http://nla.gov.au/nla.news-article1370755).', *Brisbane Courier*, accessed 26 October 2022.

Unknown (21 October 1911) '[Prison Labor](http://nla.gov.au/nla.news-article109558899)', *Tamworth Daily Observer*, accessed 26 October 2022.

Unknown (23 April 1905) '[St Helena: Gaol grievances](http://nla.gov.au/nla.news-article199300106).', *Truth*, accessed 26 October 2022.

Unknown (27 November 1916) '[An Historic Cannon](http://nla.gov.au/nla.news-article181090166).', *Daily Standard*, accessed 26 October 2022.

Unknown (4 April 1914) '[Ideal St. Helena](http://nla.gov.au/nla.news-article107481871).', *Tamworth Daily Observer*, accessed 30 October 2022.

Unknown (4 July 1867) '[Local and general news](http://nla.gov.au/nla.news-article123612954).', *Queensland Times, Ipswich Herald and General Advertiser*, accessed 29 October 2022.

Unknown (5 February 1914) '[St. Helena Prison: Plans for new buildings - indeterminate sentences](http://nla.gov.au/nla.news-article19944054)', *Brisbane Courier*, accessed 26 October 2022.

Unknown (7 April 1928) '[The St Helena Relics](http://nla.gov.au/nla.news-article79645840)', *Western Champion*, accessed 27 October 2022.

Whittington D (13 February 2021) '[Island of the damned: Dark past of Queensland's Alcatraz](https://www.couriermail.com.au/news/queensland/way-we-were-st-helena-islands-history-stained-with-brutality-madness-and-painful-death/news-story/0f9cd65c83e6dff3bc3bfe475d61422a)', *The Courier Mail website*, accessed 26 October 2022.

Whittington D (14 February 2021) '[Island of the damned: Dark past of Queensland's Alcatraz](https://www.couriermail.com.au/news/queensland/way-we-were-st-helena-islands-history-stained-with-brutality-madness-and-painful-death)', *The Courier Mail*, accessed 27 October 2022.

Whittington D (28 August 2019) '[Island groans with its penal past](https://www.yourtimemagazine.com.au/island-groans-with-its-penal-past/)', *Your Time Magazine website*, accessed 26 October 2022.

Winn C (1878) *Only known painting of St Helena Island as a working prison* [artwork], [*The remarkable story of the Helena*](http://treetopsolives.com.au/), Treetops Plantation website, accessed 15 October 2022.

Woods P (2011) *St Helena Island towards Manly* [photograph], [*Photostream*](https://www.flickr.com/photos/patriciawoods/6092565622/in/photolist-ahnSgL-ahnZuS-aho1RS)*,* flickr website, accessed 21 October 2022.
