---
title: "Thematic Analysis Discussion"
author: "Trudy Boan"
date: "2022-10-13"
output: html_document
---

\
\

### *Analysis Discussion*

The codebook generated in Taguette clearly identifies five major tags which have far more highlights than other tags. I would have to say that some of the minor tags could possibly be merged with larger tags, for example, the *crops* tag could be merged with *farm work*, and *on entry to penal establishment* could be merged with the *descriptions* tag.

I have combined here, *warders* and *goings on behind closed doors* because they had the same prominent theme, corruption, involving warders and prison gang members. Accusations of corruption involving warders were publicly aired in a newspaper article dating from 1905, continuing on until at least 1914, but probably until the closure in 1932. A released inmate lifted the lid on the fact there was a tyrannical gang network, the 'Clever Brigade' (Proscriptus 8 September 1912), who fought with 'bare knuckles' (A paying guest 12 February 1911) and was '...kept supplied by the warders and others in authority with milk and other luxuries...' (Unknown 20 August 1905). The warders appear to have supplied all inmates with prison tender, tobacco (Unknown 20 August 1905), tea, and sugar. In 1905 it was '...an open secret that it comes from the warders...' (Unknown 20 August 1905), and the question still being asked in 1911 was, if it's not the warders bringing it in, how did it get to the inmates? (A paying guest 12 February 1911). Stolen goods were being sold to warders (Unknown 20 August 1905), and they were smuggling letters from prisoners, and items from the island they could sell, such as boots made in the boot shop (Unknown 20 August 1905). One warder '...was said to have a farm, for which all the harness required was made in the prison workshops...' (A paying guest 12 February 1911).

Merging two prominent tags trades (100 highlights) and farm work (94 highlights) seems to be sensible, as both tags have the theme of labour and employment on the island. Early on men were engaged in labour-some work; clearing the island of vegetation to plant crops and erect buildings (Boggo Road Gaol Historical Society n.d.; Department of Environment and Science 2005) as well as clearing mangroves (Unknown 13 January 1869). The theme shifts in the 1870s as trade workshops were built (Boggo Road Gaol Historical Society n.d.; Department of Environment and Science 2005), the trades helping the island financially (Queensland State Archives 2021). Certain trades kept appearing in the highlights, such as tailors, boot makers, saddler's, and carpentry (Boggo Road Gaol Historical Society n.d.; Department of Environment and Science 2005; Greenhill 25 February 2022; Molloy 18 September 2007; Out of bond 26 July 1914). Analysing the highlights, less publicised trades were found. These include things like brush makers, bookbinders, candle makers, sail makers, cloth makers and masons (Department of Climate Change, Energy, the Environment and Water n.d.; K 9 November 1901).

Another theme that is clear is the disgruntlement of the inmates towards their food. Analyses show the difference in daily rations between 1878 and 1901. Early rations consisted of '...bread, maize-meal porridge, and meat' (Unknown 20 March 1878), while rations in 1901 consisted of '...20oz. of bread, 16oz. of meat. 6oz. of maize meal, 12oz. of vege-tables [*sic*], 1/2oz. of rice or barley, 3oz. of sugar, and 1/2oz. each of salt, tea, and soap' (K 9 November 1901); by 1905 tea and sugar had become an indulgence, allowed only to well-behaved inmates (Unknown 23 April 1905). In 1905 breakfast was hominy, which was '...described as simply vile...' (Unknown 23 April 1905). Men were served '...¾lb. of meat, about the same of bread, and 1/2lb. of sweet potatoes...' (Unknown 23 April 1905) for lunch and dinner was again hominy in 1905. Quality of the hominy came into disrepute at some point as there was '*The Hominy Riots*', due to '...[a] blue-mouldy, uneatable [*sic*] meal being served out...' (A paying guest 5 February 1911), presumably homily, given the name of the riot. The meat ration fared no better circa 1905, as it was explained as being '...thrown into a barrow and wheeled to the kitchen...' (Unknown 23 April 1905), in addition to being '...constantly rotten, so rotten that it could be noticed as soon as the men entered the yard' (Unknown 23 April 1905). Considering this, it may have been a godsend that the men were being given less meat than they should have been getting, '...scale[ing] only 8oz., bone included, instead of 16' (Unknown 23 April 1905). A former inmate reported that sometimes the bread was '...very raw...' (Out of bond 26 July 1914), and so bad that '...pigs would not eat [it]...' (Out of bond 26 July 1914).

Due to their questionable diet, it is no wonder escape is another prominent theme. As St Helena is an island, escape would mean swimming or rowing to the mainland, however, the waters surrounding the island were infested with sharks, and the shore of mangroves harboured mosquitoes (Keys 2020; Queensland Government 2015; Unknown 4 July 1867; Whittington 14 February 2021). One man is reported to be a victim of the sharks, an Indigenous man, Kitikir, known as Burketown Peter (Keys 2020). There is debate as to whether there were one or three successful escapes (Queensland State Archives 2016; Whittington 14 February 2021), however, in 65 years it is known that very few escapes were made (Department of Environment and Science 2005; Queensland State Archives 2016), despite attempts; using rafts, a bathtub inside a table's legs, washboard and two tubs tied with rope, dinghy, and a home made boat (Queensland State Archives 2016; Taylor 2010; Unknown 13 January 1869; Unknown 4 July 1867; Unknown 4 April 1914).

The theme of punishment was a guarantee when analysing a Penal Establishment. The later years of punishment at St Helena appear very 'easy' compared to an earlier period. Punishment post-1905 appears to be confinement to cells and being given only half rations (Queensland State Archives 2016; Unknown 23 April 1905). Punishments in the early period were severe, you could be punished for speaking, or even singing (Brismania 2019; Unknown 20 March 1878). There were the usual leg irons (Brismania 2019), and of course, flogging. The maximum number of lashes that could be issued was 50, but if more than 25 were issued, the session would need to be split into two, as '...25 was enough to see skin become bone and end at the infirmary' (Whittington 14 February 2021). There were men who were sentenced to 30 and 25 lashes for attempting to escape (Daly 2019; Unknown 4 July 1867), which was probably at the higher end of lashes. From all accounts, the worst, most feared punishment in the early period, was solitary confinement. This meant being '...sealed below ground in a metre-wide cell with only a dirt floor to sleep on, and that turned to mud when it rained' (Brismania 2019; Whittington 28 August 2019; Whittington 14 February 2021). To make things worse, it was '...pitch black and silent...28 days was enough for at least one prisoner to lose his mind' (Whittington 14 February 2021).

By far the most highlights are in the description tag. As the name suggests, the theme is about descriptions of the island, both from an inmate's perspective of former inmates and from reporters.

The themes from this analysis are important to the study of the penal establishment of St Helena. If you ask the public to name early Brisbane gaols their likely answers would be Moreton Bay penal and Boggo Road Gaol. The themes from this analysis would help to bring awareness to the St Helena Penal Establishment. The themes add to existing data and reveal information left out of the popular tourist visits. While existing data is available on punishments, labour, and food, it is typically the 'interesting' details. My analysis provides a more objective view, including all information discoverable. The theme of corruption is scarcely covered in other works, so the themes from my analysis are important in providing new ideas for further research. The digital humanities can find information quicker, provide data to more people, and provide multiple sources, details, and facts in large repositories.

\
\

References

A paying guest (12 February 1911) '[Penal Establishment and health resort: High life and hell](http://nla.gov.au/nla.news-article201756402,)', *Truth*, accessed 1 October 2022.

A paying guest (5 February 1911) '[Penal Establishment or Health Resort? High Life or Hell, Which](http://nla.gov.au/nla.news-article201758420)?', *Truth*, accessed 31 October 2022.

Boggo Road Gaol Historical Society (n.d.) '[St Helena Island Penal Establishment (1867-1932)'](https://www.boggoroadgaol.com.au/2015/10/st-helena-island.html,), *Inside Boggo Road blog*, accessed 30 October 2022.

Brismania (2019) '[Day 148: Captive audience](https://brismania.com/day-148-captive-audience/)', *Brismania blog*, accessed 30 October 2022.

Daly B (2019) '[The Wild Scotchman Part 2](https://sthelenacommunity.com.au/2019/04/15/the-wild-scotchman-part-2/)', *The St Helena Island Community blog*, accessed 29 October 2022.

Department of Climate Change, Energy, the Environment and Water (n.d.) [*St Helena Island National Park Historic Area*](https://www.environment.gov.au), Australian Heritage Database website, accessed 30 October 2022.

Department of Environment and Science (2005) [*Nature, culture and history: St Helena Island National Park*](https://parks.des.qld.gov.au/parks/st-helena-island/about/culture,), Parks and forests website, accessed 30 October 2022.

Greenhill J (25 February 2022) '[St Helena, formerly "the hell hole of the pacific](https://thecommunityleader.com.au/community-news/local-history/st-helena-formerly-the-hell-hole-of-the-pacific/)"', *The Community Leader and Real Estate New and Views*, accessed 30 October 2022.

K S (9 November 1901) '[The Isle of Unrest: H.M. Penal Establishment, St. Helena](http://nla.gov.au/nla.news-article21268213)', *Queenslander*, accessed 31 October 2022.

Keys C (2020) 'Sharing the waterways: Shark-proof swimming, penal detention and the early history of St Helena Island, Moreton Bay', *Queensland Review*, 27(2):121--136, [doi:10.1017/qre.2020.11](https://doi.org/10.1017/qre.2020.11).

Molloy S (18 September 2007) '[St Helena Island the "hell-hole of Pacific](https://www.brisbanetimes.com.au/national/queensland/st-helena-island-the-hell-hole-of-pacific-20070918-ge93t1.html,)', *Brisbane Times*, accessed 28 October 2022.

Out of bond (26 July 1914) '[Prisoners fed on sour prog. Confinee's complaints](http://nla.gov.au/nla.news-article202665223)', *Truth*, accessed 31 October 2022.

Proscriptus (8 September 1912) '[Tyrants of St. Helena: Some facts & reflections about Queensland's inferno'](http://nla.gov.au/nla.news-article201742089), *Truth*, accessed 26 October 2022.

Queensland Government (2015) [*Saint Helena Island*](https://apps.des.qld.gov.au/heritage-register/detail/?id=600315), Queensland Heritage Register website, accessed 25 October 2022.

Queensland State Archives (2016) '[The Not-So-Great-Escape](https://blogs.archives.qld.gov.au/2016/04/26/the-not-so-great-escape/)', *Stories from the Archives blog*, accessed 28 October 2022.

Queensland State Archives (2021) '[Escape from St Helena Island](https://blogs.archives.qld.gov.au/2021/04/21/escape-from-st-helena-island/)', *Stories from the Archives blog*, accessed 27 October 2022.

Taylor B (2010) [*Prisons without walls: Prison camps and penal change in Australia, c. 1913-c. 1975*](https://doi.org/10.26190/unsworks/23117) [PhD Doctorate], University of NSW, Sydney, accessed 6 October 2022.

Unknown (13 January 1869) '[From the Courier](http://nla.gov.au/nla.news-article75459987)', *Darling Downs Gazette and General Advertiser*, accessed 29 October 2022.

Unknown (20 August 1905) '[St. Helena scandals](http://nla.gov.au/nla.news-article198987032)', *Truth*, accessed 9 October 2022.

Unknown (20 March 1878) '[Life at St. Helena](http://nla.gov.au/nla.news-article1370755)', *Brisbane Courier*, accessed 25 October 2022.

Unknown (23 April 1905) '[St Helena: Gaol grievances](http://nla.gov.au/nla.news-article199300106).', *Truth*, accessed 26 October 2022.

Unknown (4 April 1914) '[Ideal St. Helena](http://nla.gov.au/nla.news-article107481871).', *Tamworth Daily Observer*, accessed 30 October 2022.

Unknown (4 July 1867) '[Local and general news](http://nla.gov.au/nla.news-article123612954).', *Queensland Times, Ipswich Herald and General Advertiser*, accessed 29 October 2022.

Whittington D (14 February 2021) '[Island of the damned: Dark past of Queensland's Alcatraz](https://www.couriermail.com.au/news/queensland/way-we-were-st-helena-islands-history-stained-with-brutality-madness-and-painful-death)', *The Courier Mail*, accessed 27 October 2022.

Whittington D (28 August 2019) '[Island groans with its penal past](https://www.yourtimemagazine.com.au/island-groans-with-its-penal-past/)', *Your Time Magazine website*, accessed 26 October 2022.
