---
title: "Harvesting data from the web"
author: "Trudy Boan"
date: "2022-10-22"
output: html_document
---

\

The dataset that I have created involves the St Helena Penal Establishment prisoner cemetery. I have used as many online sources, which were not behind a pay wall, to provide as much information about the buried prisoners; to go beyond a mere list of names and death dates. The dataset aims to humanise the name and number of as many buried prisoners as possible.

\

It must be noted however, that the names of those inmates buried at St Helena used in this dataset may be subject to change, and additions, or subtractions, made which were not available at the time of compilation. It has been noted, since 1878, that '...the names given are not always those of the deceased...' (Unknown 20 March 1878). It was noted that a '...slab of timber bears the name, age, and number of each of those beneath' (Unknown 20 March 1878). However today, the crosses made from stone or cement display only a prison number which may, or may not, correspond to those buried, and are those used in the creation of this dataset.

\

### *The dataset includes the following variables:*

[Surname]{.underline}

:   where none is provided use na

[Christian name]{.underline}

:   where none is provided use na

[Alias]{.underline}

:   names used by the inmate other than their legal names

    where none is provided use na

[Prisoner number]{.underline}

:   received by the inmate on admission

[Ethnicity]{.underline}

:   as stated in the sources

    words used are from the era and are no longer used. For example Aboriginal is no longer used.

    where none is provided use na

[Sentence]{.underline}

:   recorded as life, years and/or months

    where none is provided use na

[Where tried]{.underline}

:   the city or town the inmate was tried in after committing their crime

    where none is provided use na

[Crime]{.underline}

:   the crime that was committed by the inmate

    where none is provided use na

[Death date]{.underline}

:   -   year - where none is provided use 0 (zero)

    -   month - where none is provided use na

    -   date - where none is provided use 0 (zero)

[Queensland death record]{.underline}

:   link to the relevant source document

    sourced from Queensland birth, death and marriages website

    where none is provided use na

[Digital archive file]{.underline}

:   required as the series files found on Queensland Government ArchiveSearch, and recorded in the variable 'Source', contain multiple records per file

    this displays individual files

:   link to the direct source document relating to

    -   sentence - where none is provided use na

    -   crime - where none is provided use na

    -   place tried - where none is provided use na

    -   name and alias - where none is provided use na

    -   ethnicity - where none is provided use na

    -   prisoner number - where none is provided use 0 (zero)

[Source]{.underline}

:   link to the series files found on Queensland Government ArchiveSearch

    source that the digital archive file comes from

    where none is provided use na

[Inquest and burial sourc]{.underline}e

:   link directly to the individuals inquest and combined burial documents

    where none is provided use na

[Cause of death]{.underline}

:   the cause of death stated on death certificate for each individual

    where none is provided use na

[Source2]{.underline}

:   link to the source of the information for the 'Cause of death' variable.

    where none is provided use na

#### 

+-----------------------------------------------------------------------------+
| #### **Key data sources used to create the dataset**                        |
+=============================================================================+
| Ancestry.com website                                                        |
+-----------------------------------------------------------------------------+
| Australian Cemeteries website                                               |
+-----------------------------------------------------------------------------+
| BillionGraves website                                                       |
+-----------------------------------------------------------------------------+
| Findmypast website                                                          |
+-----------------------------------------------------------------------------+
| Queensland Government ArchiveSearch website                                 |
+-----------------------------------------------------------------------------+
| Queensland births, deaths, marriages, and divorces                          |
+-----------------------------------------------------------------------------+
| Queensland Government Open Data Portal website                              |
+-----------------------------------------------------------------------------+
|                                                                             |
+-----------------------------------------------------------------------------+
|                                                                             |
+-----------------------------------------------------------------------------+
| \*The specific series on these websites can be found in the references list |
+-----------------------------------------------------------------------------+

\

The categorical data shows that English and Aboriginal inmates are the two prominent ethnicities buried, though this may change with new data, as the number of non-disclosed ethnicities stands at 10, the same count as Aboriginal. While I expected to see ethnicities such as South Sea Islanders, Irish etc, I was surprised, for that time period, to see Greece, America and Jamaica represented.

 

When considering the amount of uncleared, unsettled area, lack of roads and railway, it is interesting to see inmates at St Helena who were tried in places like, Cooktown (today a 23 hour drive on sealed highway, 2000km from Brisbane), Hughenden (today a 16 hour drive on sealed highway, 1597km from Brisbane), Townsville (today a 16 hour drive on sealed highway, 1554km from Brisbane), Charters Towers (today a 15 hour drive on sealed highway, 1360km from Brisbane), and Clermont (today an 11 hour drive on sealed highway, 991km from Brisbane).

 

January and September are revealed as the months with the most deaths, and 1884 as the year with the most deaths -- one almost every three months. The deaths in 1884 occurred from different causes, so that rules out an endemic. One inmate, named only as Jimmy, was unfortunate enough to die on Christmas day 1889 (Levez 2016). The most common cause of death was phthisis.

\

Larceny was shown to be the crime most inmates were convicted of, followed by manslaughter. Three of the buried inmates received life sentences, and three- and five-year periods were most common for penal servitude.

\

I have learnt that having a tidy dataset is key for sharing information with others, and for others to add to your data. Simply removing white space reduces the file size, reduces errors when shared between different programs, and makes reading of the data easier. Having columns clearly labelled helps readability, and so does organisation of the columns. Having columns which relate to each other, beside each other, makes reading quicker and places complimentary data in an easy to find position. That is why I placed the source columns beside the information they relate to. Splitting columns makes interpretation easier, and helps when sharing between different programmes. Things such as date columns, instead of being in one cell, it is better to have the data split into three columns, year, month, date, or similar. Another example is names, which are easier to interpret and analyse when split into three different columns, eg. first, middle, last name. Having numerals correctly displayed as numerals, and text as text, reduces errors when sharing between programmes, and avoids misinterpretation of data. Another thing I have learnt is to keep consistent, and minimal, formatting, and consistent use of capital and lower case lettering, numeral or word for the numeral. I have learnt that having a tidy dataset makes the data more accessible to more people.

\
\
\

References

Ancestry.com (n.d.) [*Queensland, Australia, Death Inquest Index, 1859-1897*](https://www.ancestry.com.au/search/collections/70807/), Ancestry.com website, accessed 3 September 2022.

Findmypast (n.d.) [*Search Results for Queensland, St Helena Convict Index 1863-1936*](https://www.findmypast.com/search/results?datasetname=queensland%2c+st+helena+convict+index+1863-1936&sid=103), Findmypast website, accessed 22 October 2022.

Levez J (2016) [*Prisoner #3650 Jimmy*](https://billiongraves.com/grave/Prisoner-%233650-Jimmy/18398259), BillionGraves website, accessed 24 October 2022.

Levez J (n.d.) [*St Helena Penal Establishment Prisoners Cemetery*](https://billiongraves.com/cemetery/St-Helena-Penal-Establishment-Prisoners-Cemetery/294279), BillionGraves website, accessed 17 October 2022.

Levez J and Penny L (2016) [*St Helena Penal Establishment Prisoner Cemetery*, Australian Cemeteries website](http://www.australiancemeteries.com.au/qld/brisbane/st_helena/st_helena_prisoners_data.htm), accessed 5 October 2022.

Queensland Government (2022) [*Inquests 1859 to 1902*](https://www.data.qld.gov.au/dataset/inquests-1859-to-1902), Queensland Government Open Data Portal website, accessed 12 October 2022.

Queensland Government (n.d.) [*Barker George*](https://www.archivessearch.qld.gov.au/items/ITM2732765), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Billy*](https://www.archivessearch.qld.gov.au/items/ITM2731612), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Chick John*](https://www.archivessearch.qld.gov.au/items/ITM2723189), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Collins Edward*](https://www.archivessearch.qld.gov.au/items/ITM2735171), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Collins William*](https://www.archivessearch.qld.gov.au/items/ITM2725725), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Coronial Files (Inquests and No Inquests)*](https://www.archivessearch.qld.gov.au/series/S36), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Crown Tim*](https://www.archivessearch.qld.gov.au/items/ITM2733594), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Dean Henry*](https://www.archivessearch.qld.gov.au/items/ITM2732771), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Downs Archibald*](https://www.archivessearch.qld.gov.au/items/ITM2731328), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Family history research service*](https://www.familyhistory.bdm.qld.gov.au/,), Births, deaths, marriages, and divorces website, accessed 22 October 2022.

Queensland Government (n.d.) [*Forka*](https://www.archivessearch.qld.gov.au/items/ITM2735702), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*General record and description of male prisoners - HM Penal Establishment, St Helena*](https://www.archivessearch.qld.gov.au/items/ITM92277), ArchivesSearch website, accessed 26 October 2022.

Queensland Government (n.d.) [*Hayes John*](https://www.archivessearch.qld.gov.au/items/ITM2725548), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Herrlick John*](https://www.archivessearch.qld.gov.au/items/ITM2723358), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Jamerson William*](https://www.archivessearch.qld.gov.au/items/ITM2734778), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Jimmy*](https://www.archivessearch.qld.gov.au/items/ITM2730160), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Jones John*](https://www.archivessearch.qld.gov.au/items/ITM2723056), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Loder John*](https://www.archivessearch.qld.gov.au/items/ITM2722068), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Lover Samuel*](https://www.archivessearch.qld.gov.au/items/ITM2729740), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Mayall George*](https://www.archivessearch.qld.gov.au/items/ITM2733865), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*McGoldrich Samuel*](https://www.archivessearch.qld.gov.au/items/ITM2731103), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Mitchel Joseph*](https://www.archivessearch.qld.gov.au/items/ITM2731742), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Moore George*](https://www.archivessearch.qld.gov.au/items/ITM2729269), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Moss Valentine*](https://www.archivessearch.qld.gov.au/items/ITM2722925), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Muller Harry*](https://www.archivessearch.qld.gov.au/items/ITM2736026), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Potts William*](https://www.archivessearch.qld.gov.au/items/ITM2727699), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Rahree*](https://www.archivessearch.qld.gov.au/items/ITM2735293), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Register of male prisoners admitted - H. M. Penal Establishment/Gaol, St Helena*](https://www.archivessearch.qld.gov.au/items/ITM92272), ArchivesSearch website, accessed 22 October 2022.

Queensland Government (n.d.) [*Rickaby Henry*](https://www.archivessearch.qld.gov.au/items/ITM2733765), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Stapleton Thomas*](https://www.archivessearch.qld.gov.au/items/ITM2733864), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Tidy Richard*](https://www.archivessearch.qld.gov.au/items/ITM2723032), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Tommah Tom*](https://www.archivessearch.qld.gov.au/items/ITM2728493), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Waipieta David*](https://www.archivessearch.qld.gov.au/items/ITM2731612), ArchivesSearch website, accessed 27 October 2022.

Queensland Government (n.d.) [*Wyndham John*](https://www.archivessearch.qld.gov.au/items/ITM2723432), ArchivesSearch website, accessed 27 October 2022.

Unknown (20 March 1878) '[Life at St. Helena](http://nla.gov.au/nla.news-article1370755)', *Brisbane Courier*, accessed 26 October 2022.
